"0": "find board & press button"
"1": "move slider to setpoints on screen"
"2": "plug in probe into test port"
"3": "open door, probe circuit"
"4": "wrap cable, replace probe"
"5": "press stop trial button"